### ISSUE TITLE
Add velocity in encoding

### ISSUE THREAD

**Issue by ArikaGrimmer** [RetroCirce/Music-SketchNet#15]
Hi, I just wonder is it possible to add velocity when encoding the midi files?

**Comment by RetroCirce** [comment]
Hi,

For this project encoding method, it is not easy to add the velocity.
But some following works using transformer architecture and advanced representations of music (in 2021, 2022 year) are possible to do that.
You can follow this two papers (by google): Pop Music Transformer, and Compound Word Transformer

**Comment by ArikaGrimmer** [comment]
Got it, thank you!

**Comment by ArikaGrimmer** [comment]
Got it, thank you!
